### ISSUE TITLE
preserve line breaks in the 'tombstone' field

### ISSUE THREAD

**Issue by tacman** [ClevelandMuseumArt/openaccess#10]
The tombstone field in the JSON would be nicer if it had linebreaks, which could then be formatted to look like a traditional printed tombstone:

> A Miller's Carriage, c. 1895. Albert-Charles Lebourg (French, 1849–1928). Black and white chalk with stumping on beige wove paper; sheet: 33.2 x 49.7 cm (13 1/16 x 19 9/16 in.). The Cleveland Museum of Art, Bequest of Muriel Butkin 2015.449

Nicer if each line were separate

```
A Miller's Carriage, c. 1895. 
Albert-Charles Lebourg (French, 1849–1928). 
Black and white chalk with stumping on beige wove paper; sheet: 33.2 x 49.7 cm (13 1/16 x 19 9/16 in.). 
The Cleveland Museum of Art, Bequest of Muriel Butkin 2015.449
```

I realize that all those fields are individually available as well, but if it's trivial for you to format it, it'd be helpful.

**Comment by JCACMA** [comment]
Dear Tac,
Thank you for your suggestion. As you mentioned, you can create your own tombstone in your preferred format by pulling individual fields such as artist, date, etc. Many people have various ways of presenting survey collections online for multiple museums. The created "Tomb Stone" field provides a convenient option for those needing a quick caption to identify an image.
Example:

***@***.***


Best,
Jane

Jane Alexander
T 216-707-2644
From: Tac Tacelosky ***@***.***>
Sent: Tuesday, July 16, 2024 1:23 PM
To: ClevelandMuseumArt/openaccess ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ClevelandMuseumArt/openaccess] preserve line breaks in the 'tombstone' field (Issue #10)


The tombstone field in the JSON would be nicer if it had linebreaks, which could then be formatted to look like a traditional printed tombstone:

A Miller's Carriage, c. 1895. Albert-Charles Lebourg (French, 1849-1928). Black and white chalk with stumping on beige wove paper; sheet: 33.2 x 49.7 cm (13 1/16 x 19 9/16 in.). The Cleveland Museum of Art, Bequest of Muriel Butkin 2015.449

Nicer if each line were separate

A Miller's Carriage, c. 1895.

Albert-Charles Lebourg (French, 1849-1928).

Black and white chalk with stumping on beige wove paper; sheet: 33.2 x 49.7 cm (13 1/16 x 19 9/16 in.).

The Cleveland Museum of Art, Bequest of Muriel Butkin 2015.449

I realize that all those fields are individually available as well, but if it's trivial for you to format it, it'd be helpful.

-

**Comment by tacman** [comment]
Understood, thanks!

**Comment by tacman** [comment]
For anyone, including my future self, wanting to know how to re-create the tombstone from the records, here's how I did it in twig:

```twig
{{ artwork.description }}
<b>{{ artwork.culture|join("\n") }}</b>

<i>{{ artwork.technique }}</i>
<i>{{ artwork.measurements }}</i>

{% if artwork.did_you_know %}
Did you know...
{{ artwork.did_you_know }}
{% endif %}

{{ artwork.creditline }}
<a href="{{ artwork.url() }}" target="_blank">{{ artwork.url() }}</a>
```

I used this template to publish the description on Flickr, e.g. https://www.flickr.com/photos/museado/53861802028/ to make it more readable:

![image](https://github.com/user-attachments/assets/d6fcd657-ada0-428a-bd9c-2beead334fe2)

Or with a description:

![image](https://github.com/user-attachments/assets/2f4ab5ad-944b-48c8-a6c0-9640c84f1506)

https://www.flickr.com/photos/museado/53863258875
