### ISSUE TITLE
website down for individual object pages

### ISSUE THREAD

**Issue by tacman** [ClevelandMuseumArt/openaccess#12]
https://www.clevelandart.org/art/1928.659

![image](https://github.com/user-attachments/assets/245db196-077d-4472-a206-1c39196a9242)

Also https://www.clevelandart.org/art/2017.214

Perhaps this is related to the redesign? https://www.clevelandart.org/digital-innovations/our-redesigned-website

On a related note, can you add a date to that page?  When was the website redesigned.

All of the Flickr pages have links back to clevelandart.org, and none of  them are working now.  These are the urls provided in the JSON from this repo.

**Comment by thomps9012** [comment]
@tacman  thanks for flagging this, our frontend team is currently working on a solution.
We'll keep you appraised of any updates & developments.

**Comment by tacman** [comment]
Everything appears to be working again.
