### ISSUE TITLE
wording promotes using wrong query parameter to get only CC0 artworks

### ISSUE THREAD

**Issue by JustinGOSSES** [ClevelandMuseumArt/openaccess#2]
A small point...
I noticed on http://openaccess-api.clevelandart.org/  The wording in the line
`cc0 | integer | 0 or 1. Determines whether only CC0 artworks or returned or only not CC0 artworks.`
is confusing. Based on the ordering, I would have suspected that 0 is only CC0 artworks, but in fact CC0 artworks are retuned by 1.

To avoid confusion, maybe changed wording to: 
`0 or 1. Using 1 returns only CC0 artworks and 0 returns only artworks that have a license other than CC0.`

**Comment by ethanholda** [comment]
I changed the language on this to (hopefully) make it clearer.

**Comment by JustinGOSSES** [comment]
There is an extra 'or' now.

`0 or 1. Determines whether non-CC0 artworks or returned or only CC0 artworks.`

try
`
0 or 1. Determines whether only non-CC0 artworks returned or only CC0 artworks returned.
`

**Comment by ClevelandArtGIT** [comment]
Typo. Should be fixed now.
