### ISSUE TITLE
CORS header response should be changed to allow cross-origin responses

### ISSUE THREAD

**Issue by JustinGOSSES** [ClevelandMuseumArt/openaccess#3]
CORS header response should be changed to allow cross-origin responses.

Right now you can't fetch data from the API from an url like https://thisIsNotTheCMAbutIBuiltThisCoolThingWithTheirData.com
This prevents people from building websites that call your API directly. 

Example:
https://beta.observablehq.com/@justingosses/cleveland-museum-of-art-api-test-yard-1

How to fix:
https://enable-cors.org/index.html

**Comment by JustinGOSSES** [comment]
Fixed! Thank you

**Comment by beogip** [comment]
Hi, I'm experiencing CORS issues. Three days ago was everything working

**Comment by saxenanurag** [comment]
Hello @beogip 
Can you please share the error you are getting? 
Any other data, such as the URL that you are trying to access, will be helpful. Thank you.
